version: '3'
services:
  db:
    build: ./container/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./container/db/data:/var/lib/mysql
      - ./container/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # [/docker-entrypoint-initdb.d]ディレクトリ内のSQLがコンテナ起動時に実行される
      - ./container/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  backend:
    build: ./backend
    ports:
      # API用のポートを開く
      - '23450:8080'
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '8080:8080'
  web:
    build: ./container/web
    ports:
      - '80:80'
    volumes:
      # ログをコピー
      - ./container/web/log:/var/log/nginx/
      # フロントエンドをデプロイ
      # - ./frontend/dist:/usr/share/nginx/html
volumes:
  data: {}
