version: '3'
services:
  servlet:
    build: ./container/servlet
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/local/tomcat/webapps/app
    command: bash -c 'javac -classpath /usr/local/tomcat/lib/servlet-api.jar ./webapps/app/WEB-INF/classes/mypackage/Hello.java && catalina.sh run'
volumes:
  data: {}
