version: '3'
services:
  servlet:
    build: ./container/servlet
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/local/tomcat/webapps/app
  web:
    build: ./container/web
    ports:
      - '80:80'
    volumes:
      - ./container/web/log:/var/log/nginx/
volumes:
  data: {}
